# Site settings
title: *folio
email:  yellin han's blog
description: > # this means to ignore newlines until "baseurl:"
  yerin han's blog
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  poetry:
    output: true
    permalink: /blog/:path/

