# Site settings
title: yellin's blog
email: hanyerin24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  yellin's blog
baseurl:
url:  yerinhan.github.io
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  
